version: '3.4'

services:
  web:
    image: bozhimirov/pomarinascouts
    build: PomarinaScouts
    command: gunicorn PomarinaScouts.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/PomarinaScouts/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bozhimirov
      POSTGRES_USER: sakral
      POSTGRES_DB: database_name_new
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
