# Generated by Django 4.1.3 on 2022-11-28 21:06

import Scouts.core.model_mixins
import Scouts.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='kids_photos/', validators=[Scouts.core.validators.validate_file_less_than_5mb])),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), Scouts.core.validators.validate_only_numbers])),
                ('parent_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=60, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(Scouts.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
