# Generated by Django 4.1.3 on 2022-12-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_alter_kid_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['-age']},
        ),
    ]
