# Generated by Django 4.1.3 on 2022-12-08 23:50

import Scouts.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_alter_kid_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='date_of_birth',
            field=models.DateField(help_text='Please Use Format YYYY-MM-DD:', validators=[Scouts.core.validators.validate_birth_credentials]),
        ),
        migrations.AlterField(
            model_name='kid',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), Scouts.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Please choose', max_length=6),
        ),
        migrations.AlterField(
            model_name='kid',
            name='last_name',
            field=models.CharField(blank=True, help_text='Optional / Last Name', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), Scouts.core.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='kid',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Optional / Kid's Personal Phone Number", max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), Scouts.core.validators.validate_only_numbers]),
        ),
        migrations.AlterField(
            model_name='kid',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional / Upload Profile Picture', null=True, upload_to='kids_photos/', validators=[Scouts.core.validators.validate_file_less_than_5mb]),
        ),
    ]
