# Generated by Django 4.1.3 on 2022-12-10 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_alter_kid_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='kid',
            name='last_name',
            field=models.CharField(blank=True, help_text='Optional / Last Name', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
