# Generated by Django 4.1.3 on 2022-12-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_alter_kid_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.CharField(choices=[('required', 'Required / Please choose'), ('male', 'Male'), ('female', 'Female')], default='required', help_text='Required / Please choose', max_length=8),
        ),
    ]
