# Generated by Django 4.1.3 on 2022-12-10 22:35

import Scouts.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0014_alter_kid_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Required / Please choose gender', max_length=6),
        ),
        migrations.AlterField(
            model_name='kid',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Optional / Kid's Personal Phone Number", max_length=10, null=True, validators=[Scouts.core.validators.validate_mobile_number, Scouts.core.validators.validate_only_numbers]),
        ),
    ]
