# Generated by Django 4.1.3 on 2022-12-12 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0015_alter_kid_gender_alter_kid_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional / Upload Profile Picture', max_length=255, null=True),
        ),
    ]
