# Generated by Django 4.1.3 on 2022-12-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0016_alter_kid_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='gender',
            field=models.CharField(choices=[(None, 'Required / Please choose gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=31),
        ),
    ]
