# Generated by Django 4.1.3 on 2022-12-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0019_kid_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='parent',
        ),
    ]
