# Generated by Django 4.1.3 on 2022-12-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_useditem_price_alter_useditem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='useditem',
            options={'ordering': ['slug']},
        ),
    ]
