# Generated by Django 4.1.3 on 2022-12-09 10:31

import Scouts.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ages',
            field=models.CharField(blank=True, choices=[('Beavers', 'Beavers'), ('Cubs', 'Cubs'), ('Scouts', 'Scouts'), ('Ventures', 'Ventures'), ('Rovers', 'Rovers'), ('AdultVolunteer', 'Adult Volunteer'), ('SmallKids', 'Beavers & Cubs'), ('TeenKids', 'Scouts & Ventures'), ('Adults', 'Rovers & Volunteers')], help_text='Optional / Please choose Age category ', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Others', 'Others')], help_text='Required / Please choose category of the item', max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, help_text='Optional / Description of the Item ', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Optional / Please choose Gender category ', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Optional / Location of the Item ', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, help_text='Optional / Name of the item ', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(help_text='Required / Upload photo of your Item here!', upload_to='items_photos/', validators=[Scouts.core.validators.validate_file_less_than_5mb]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(help_text='Required / Price of the item ', validators=[Scouts.core.validators.validate_gt_zero]),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], help_text='Optional / Please choose Size category ', max_length=4, null=True),
        ),
    ]
