# Generated by Django 4.1.3 on 2022-12-09 15:06

import Scouts.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useditem',
            name='photo',
            field=models.ImageField(help_text='Required / Upload photo of your Item here!', upload_to='used_items_photos/', validators=[Scouts.core.validators.validate_file_less_than_5mb]),
        ),
    ]
