# Generated by Django 4.1.3 on 2022-12-12 16:20

import Scouts.core.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_item_ages_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload photo of your Item here!', max_length=255),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='photo',
            field=cloudinary.models.CloudinaryField(help_text='Required / Upload photo of your Item here!', max_length=255, validators=[Scouts.core.validators.validate_file_less_than_5mb]),
        ),
    ]
