# Generated by Django 4.1.3 on 2022-12-13 08:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_item_photo_alter_useditem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('SoftShell', 'Soft Shell'), ('Others', 'Others')], help_text='Required / Please choose category of the item', max_length=9),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='category',
            field=models.CharField(choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('SoftShell', 'Soft Shell'), ('Others', 'Others')], help_text='Required / Please choose category of the item', max_length=9),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='photo',
            field=cloudinary.models.CloudinaryField(help_text='Required / Upload photo of your Item here!', max_length=255),
        ),
    ]
