# Generated by Django 4.1.3 on 2022-12-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_item_category_alter_useditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Trousers', 'Trousers'), ('SoftShell', 'Soft Shell'), ('Others', 'Others')], help_text='Required / Please choose category of the item', max_length=9),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='category',
            field=models.CharField(choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Trousers', 'Trousers'), ('SoftShell', 'Soft Shell'), ('Others', 'Others')], help_text='Required / Please choose category of the item', max_length=9),
        ),
    ]
