# Generated by Django 4.1.3 on 2022-12-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_alter_item_category_alter_useditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ages',
            field=models.CharField(blank=True, choices=[(None, 'Optional / Please choose ages category'), ('Beavers', 'Beavers'), ('Cubs', 'Cubs'), ('Scouts', 'Scouts'), ('Ventures', 'Ventures'), ('Rovers', 'Rovers'), ('Adult Volunteer', 'Adult Volunteer'), ('Beavers & Cubs', 'Beavers & Cubs'), ('Scouts & Ventures', 'Scouts & Ventures'), ('Rovers & Volunteers', 'Rovers & Volunteers')], max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[(None, 'Optional / Please choose category of the item'), ('Hoodies', 'Hoodies'), ('T-shirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Trousers', 'Trousers'), ('Soft Shell', 'Soft Shell'), ('Others', 'Others')], max_length=45),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Optional / Please choose gender category'), ('Male', 'Male'), ('Female', 'Female')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[(None, 'Optional / Please choose size category'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='ages',
            field=models.CharField(blank=True, choices=[(None, 'Optional / Please choose ages category'), ('Beavers', 'Beavers'), ('Cubs', 'Cubs'), ('Scouts', 'Scouts'), ('Ventures', 'Ventures'), ('Rovers', 'Rovers'), ('Adult Volunteer', 'Adult Volunteer'), ('Beavers & Cubs', 'Beavers & Cubs'), ('Scouts & Ventures', 'Scouts & Ventures'), ('Rovers & Volunteers', 'Rovers & Volunteers')], max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='category',
            field=models.CharField(choices=[(None, 'Required / Please choose category of the item'), ('Hoodies', 'Hoodies'), ('T-shirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Trousers', 'Trousers'), ('Soft Shell', 'Soft Shell'), ('Others', 'Others')], max_length=45),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Optional / Please choose gender category'), ('Male', 'Male'), ('Female', 'Female')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useditem',
            name='size',
            field=models.CharField(blank=True, choices=[(None, 'Optional / Please choose size category'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=38, null=True),
        ),
    ]
