# Generated by Django 4.1.3 on 2022-11-29 20:12

import Scouts.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(help_text='Please use only letters.', max_length=30, validators=[django.core.validators.MinLengthValidator(2), Scouts.core.validators.validate_only_letters])),
                ('last_name', models.CharField(help_text='Please use only letters.', max_length=30, validators=[django.core.validators.MinLengthValidator(2), Scouts.core.validators.validate_only_letters])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), Scouts.core.validators.validate_only_numbers])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users_photos', validators=[Scouts.core.validators.validate_file_less_than_5mb])),
            ],
        ),
    ]
