# Generated by Django 4.1.3 on 2022-12-04 15:13

import Scouts.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0002_alter_profile_gender_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(error_messages={'required': 'Place phone number in format: 0987654321'}, help_text='Type phone number in format: 0987654321', max_length=10, validators=[Scouts.core.validators.validate_mobile_number, Scouts.core.validators.validate_only_numbers]),
        ),
    ]
