# Generated by Django 4.1.3 on 2022-12-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0005_alter_profile_first_name_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='Optional / Please choose', help_text='Optional / Please choose', max_length=6, null=True),
        ),
    ]
