# Generated by Django 4.1.3 on 2022-12-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0012_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Optional / Please choose gender', max_length=6, null=True),
        ),
    ]
