# Generated by Django 4.1.3 on 2022-12-12 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0014_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional / Upload your photo here', max_length=255, null=True),
        ),
    ]
