# Generated by Django 4.1.3 on 2022-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0015_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Your String For Display'), ('Male', 'Male'), ('Female', 'Female')], help_text='Optional / Please choose gender', max_length=100, null=True),
        ),
    ]
