# Generated by Django 4.1.3 on 2022-11-28 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('MonthlyTax', 'Monthly Tax'), ('AnnualFee', 'Annual Fee')], max_length=10)),
                ('staff_member', models.CharField(max_length=100)),
                ('tax_per_kid', models.PositiveIntegerField(blank=True, null=True)),
                ('period_billed', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('generated_date', models.DateField(auto_now=True)),
                ('confirmed_by_user', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('confirmed_by_staff', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('kid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_kid_type', to='kids.kid')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
