# Generated by Django 4.1.3 on 2022-12-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid', 'confirmed_by_user', 'generated_date']},
        ),
    ]
