# Generated by Django 4.1.3 on 2022-12-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_alter_kid_slug'),
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional / Comments on payment', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kid',
            field=models.ForeignKey(blank=True, help_text='Required / Select Kid to generate payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_kid_type', to='kids.kid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='model_name',
            field=models.CharField(choices=[('MonthlyTax', 'Monthly Tax'), ('AnnualFee', 'Annual Fee')], help_text='Required / Select payment type', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period_billed',
            field=models.CharField(help_text='Required / Billed period', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax_per_kid',
            field=models.PositiveIntegerField(blank=True, help_text='Required / Tax depending of number of kids per parent', null=True),
        ),
    ]
