# Generated by Django 4.1.3 on 2022-12-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='model_name',
            field=models.CharField(choices=[(None, 'Required / Select payment type'), ('Monthly Tax', 'Monthly Tax'), ('Annual Fee', 'Annual Fee')], max_length=100),
        ),
    ]
