# Generated by Django 4.1.3 on 2022-11-28 21:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Others', 'Others')], max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ages', models.CharField(choices=[('Beavers', 'Beavers'), ('Cubs', 'Cubs'), ('Scouts', 'Scouts'), ('Ventures', 'Ventures'), ('Rovers', 'Rovers'), ('AdultVolunteer', 'Adult Volunteer'), ('SmallKids', 'Beavers & Cubs'), ('TeenKids', 'Scouts & Ventures'), ('Adults', 'Rovers & Volunteers')], max_length=14)),
                ('size', models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('place_to_deliver', models.CharField(choices=[('Office', 'Office'), ('Other', 'I will provide details in comments')], max_length=6)),
                ('comments', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('publication_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
