# Generated by Django 4.1.3 on 2022-12-02 14:39

import Scouts.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(validators=[Scouts.core.validators.validate_gt_zero]),
        ),
    ]
