# Generated by Django 4.1.3 on 2022-12-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_confirmed_by_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff_member_finished',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
