# Generated by Django 4.1.3 on 2022-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_staff_member_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
