# Generated by Django 4.1.3 on 2022-12-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_additional_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='staff_member_finished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
