# Generated by Django 4.1.3 on 2022-12-09 10:56

import Scouts.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_comment',
            field=models.CharField(blank=True, default='ok', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ages',
            field=models.CharField(choices=[('Beavers', 'Beavers'), ('Cubs', 'Cubs'), ('Scouts', 'Scouts'), ('Ventures', 'Ventures'), ('Rovers', 'Rovers'), ('AdultVolunteer', 'Adult Volunteer'), ('SmallKids', 'Beavers & Cubs'), ('TeenKids', 'Scouts & Ventures'), ('Adults', 'Rovers & Volunteers')], help_text='Required / Please choose ages category', max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Others', 'Others')], help_text='Required / Please choose category of the item', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments on order or place to receive', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Optional / Please choose gender category', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(blank=True, help_text='Optional / Name of the item', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_to_deliver',
            field=models.CharField(choices=[('Office', 'Office'), ('Other', 'I will provide details in comments')], help_text='Required / Please choose place to receive item', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Required / Please choose quantity of item', validators=[Scouts.core.validators.validate_gt_zero]),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], help_text='Optional / Please choose size category', max_length=4, null=True),
        ),
    ]
