# Generated by Django 4.1.3 on 2022-12-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_additional_comment_alter_order_ages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments on order or place to receive', max_length=300, null=True),
        ),
    ]
