# Generated by Django 4.1.3 on 2022-12-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_ages_alter_order_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ages',
            field=models.CharField(choices=[('required', 'Required / Please choose Age range'), ('Beavers', 'Beavers'), ('Cubs', 'Cubs'), ('Scouts', 'Scouts'), ('Ventures', 'Ventures'), ('Rovers', 'Rovers'), ('AdultVolunteer', 'Adult Volunteer'), ('SmallKids', 'Beavers & Cubs'), ('TeenKids', 'Scouts & Ventures'), ('Adults', 'Rovers & Volunteers')], default='required', max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('required', 'Required / Please choose category'), ('Hoodies', 'Hoodies'), ('Tshirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Hats', 'Hats'), ('Scarves', 'Scarves'), ('Others', 'Others')], default='required', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, choices=[('optional', 'Optional / Please choose gender'), ('male', 'Male'), ('female', 'Female')], default='optional', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_to_deliver',
            field=models.CharField(choices=[('required', 'Required / Please choose place to receive item'), ('Office', 'Office'), ('Other', 'I will provide details in comments')], default='required', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, choices=[('optional', 'Optional / Please choose Size'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='optional', max_length=8, null=True),
        ),
    ]
