# Generated by Django 4.1.3 on 2022-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_ages_alter_order_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='publication_date',
            field=models.DateField(auto_now=True, verbose_name='date created'),
        ),
    ]
