# Generated by Django 4.1.3 on 2022-12-13 08:49

import Scouts.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Required / Please choose quantity of item', max_length=200, validators=[Scouts.core.validators.validate_gt_zero, Scouts.core.validators.validate_max_quantity]),
        ),
    ]
